server:
  port: 8002
spring:
  application:
    name: spring-cloud-alibaba-stock # 应用名称, nacos会将名称当做服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: adb6f806-e08a-41c0-9160-f63d6ac6a732 # 命名空间, 主要用于区分环境 dev/sit/prev/prod
        group: material # 组名称, 一般用于区分项目
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      web-context-unify: false # 默认true, 将调用链路收敛
logging:
  level:
    com.maple.stock.feign: debug # 指定该路径下的日志界别为debug----本地开发时配置
feign:
  client:
    config:
      spring-cloud-alibaba-user: # 被调用服务在nacos中注册的应用名
        # 日志级别
        logger-level: FULL
        # 连接超时时间 默认 2s
        connect-timeout: 5000
        # 请求处理超时时间 默认5s
        read-timeout: 10000
