server:
  port: 8014
spring:
  application:
    name: sharding-jdbc-demo
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    mode:
      type: Memory
    props:
      sql-show: true
    datasource:
      sharding:
        default-data-source-name: m1
      names: m1,m2
#      m0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://${ENV_CLOUD_IP}:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: 123456
      m1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${ENV_CLOUD_IP}:3307/sharding_1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      m2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${ENV_CLOUD_IP}:3307/sharding_2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
    rules:
      sharding:
        key-generators:
          my_id_for_snowflake_alg:
            type: SNOWFLAKE
            props:
              worker:
                id: 1
        tables:
#          user:
#            actual-data-nodes: m0.user
          t_order:
            actual-data-nodes: m1.t_order
          item:
            actual-data-nodes: m1.item
          course:
            actual-data-nodes: m$->{[1,2]}.course_$->{0..2}
            database-strategy:
#              standard:
#                sharding-algorithm-name: db_standard_alg
#                sharding-column: id
#              complex:
#                sharding-columns: id,user_id
#                sharding-algorithm-name: db_complex_alg
#              hint:
#                sharding-algorithm-name: db_hint_alg
#            table-strategy:
#              standard:
#                sharding-column: id
#                sharding-algorithm-name: table_standard_alg
#              complex:
#                sharding-columns: id,user_id
#                sharding-algorithm-name: table_complex_alg
#              hint:
#                sharding-algorithm-name: table_hint_alg
              standard:
                sharding-algorithm-name: db_class_base_standard_alg
                sharding-column: id
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: table_class_base_standard_alg
        sharding-algorithms:
          db_standard_alg:
            type: INLINE
            props:
              algorithm-expression: m$->{id % 2 + 1}
              allow-range-query-with-inline-sharding: true
          db_complex_alg:
            type: COMPLEX_INLINE
            props:
              algorithm-expression: m$->{(id + user_id) % 2 + 1}
              allow-range-query-with-inline-sharding: true
          db_hint_alg:
            type: HINT_INLINE
            props:
              algorithm-expression: m$->{value}
          db_class_base_standard_alg:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.maple.sharding.algorithm.MyDbStandardAlgorithm
          table_standard_alg:
            type: INLINE
            props:
              algorithm-expression: course_$->{id % 3}
              allow-range-query-with-inline-sharding: true
          table_complex_alg:
            type: COMPLEX_INLINE
            props:
              algorithm-expression: course_$->{(id + user_id) % 3}
              allow-range-query-with-inline-sharding: true
          table_hint_alg:
            type: HINT_INLINE
            props:
              algorithm-expression: course_$->{value}
          table_class_base_standard_alg:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.maple.sharding.algorithm.MyTbStandardAlgorithm
        default-key-generate-strategy:
          column: id
          key-generator-name: my_id_for_snowflake_alg
        default-database-strategy:
          standard:
            sharding-algorithm-name: db_standard_alg
            sharding-column: id
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.maple.mp.entity
