server:
  port: 8014
spring:
  application:
    name: sharding-jdbc-demo
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    mode:
      type: Memory
    props:
      sql-show: true
    datasource:
      sharding:
        default-data-source-name: m1
      names: m1,m2,s1,s2
      m1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${ENV_CLOUD_IP}:3307/sharding_1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      m2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${ENV_CLOUD_IP}:3307/sharding_2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      s1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${ENV_CLOUD_IP}:3308/sharding_1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      s2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${ENV_CLOUD_IP}:3308/sharding_2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
    rules:
      readwrite-splitting:
        data-sources:
          mrw1:
            type: Static
            props:
              write-data-source-name: m1
              read-data-source-names: s1
            load-balancer-name: alg_round
          mrw2:
            type: Static
            props:
              write-data-source-name: m2
              read-data-source-names: s2
            load-balancer-name: alg_round
        load-balancers:
          alg_round:
            type: ROUND_ROBIN
      sharding:
        key-generators:
          my_id_for_snowflake_alg:
            type: SNOWFLAKE
            props:
              worker:
                id: 1
        tables:
          value_set_item:
            actual-data-nodes: mrw$->{[1,2]}.value_set_item
          course:
            actual-data-nodes: mrw$->{[1,2]}.course_$->{0..2}
            database-strategy:
              standard:
                sharding-algorithm-name: db_standard_alg
                sharding-column: id
#              complex:
#                sharding-columns: id,user_id
#                sharding-algorithm-name: db_complex_alg
#              hint:
#                sharding-algorithm-name: db_hint_alg
#              standard:
#                sharding-algorithm-name: db_class_base_standard_alg
#                sharding-column: id
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: table_standard_alg
#              complex:
#                sharding-columns: id,user_id
#                sharding-algorithm-name: table_complex_alg
#              hint:
#                sharding-algorithm-name: table_hint_alg
#              standard:
#                sharding-column: id
#                sharding-algorithm-name: table_class_base_standard_alg
        sharding-algorithms:
          db_standard_alg:
            type: INLINE
            props:
              algorithm-expression: mrw$->{id % 2 + 1}
              allow-range-query-with-inline-sharding: true
          db_complex_alg:
            type: COMPLEX_INLINE
            props:
              algorithm-expression: mrw$->{(id + user_id) % 2 + 1}
              allow-range-query-with-inline-sharding: true
          db_hint_alg:
            type: HINT_INLINE
            props:
              algorithm-expression: mrw$->{value}
          db_class_base_standard_alg:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.maple.sharding.algorithm.MyDbStandardAlgorithm
          table_standard_alg:
            type: INLINE
            props:
              algorithm-expression: course_$->{id % 3}
              allow-range-query-with-inline-sharding: true
          table_complex_alg:
            type: COMPLEX_INLINE
            props:
              algorithm-expression: course_$->{(id + user_id) % 3}
              allow-range-query-with-inline-sharding: true
          table_hint_alg:
            type: HINT_INLINE
            props:
              algorithm-expression: course_$->{value}
          table_class_base_standard_alg:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.maple.sharding.algorithm.MyTbStandardAlgorithm
        default-key-generate-strategy:
          column: id
          key-generator-name: my_id_for_snowflake_alg
        default-database-strategy:
          standard:
            sharding-algorithm-name: db_standard_alg
            sharding-column: id
        broadcast-tables: value_set_item
      encrypt:
        tables:
          user:
            columns:
              password:
#                plainColumn: password_plain # 存储明文的字段
                cipherColumn: password # 存储密文的字段
                encryptorName: user_password_encrypt2 # 指定加密策略
        encryptors:
#          user_password_encrypt1:
#            type: AES
#            props:
#              aes-key-value: 123456
#              digest-algorithm-name: SHA-1
          user_password_encrypt2:
            type: MD5
          user_password_encrypt3:
            type: SM3
            props:
              sm3-salt: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.maple.mp.entity
  global-config:
    db-config:
      id-type: auto
